import type { TarotCardType, Spread, Language } from './types';

const BASE_URL = "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/";

export const tarotDeck: TarotCardType[] = [
  // Major Arcana
  { id: 0, name: { en: "The Fool", ru: "Шут" }, imageUrl: `${BASE_URL}00_fool.png`, description: { en: "New beginnings, innocence, spontaneity.", ru: "Новые начинания, невинность, спонтанность." } },
  { id: 1, name: { en: "The Magician", ru: "Маг" }, imageUrl: `${BASE_URL}01_magician.png`, description: { en: "Manifestation, resourcefulness, power.", ru: "Проявление, находчивость, сила." } },
  { id: 2, name: { en: "The High Priestess", ru: "Жрица" }, imageUrl: `${BASE_URL}02_high_priestess.png`, description: { en: "Intuition, sacred knowledge, divine feminine.", ru: "Интуиция, священное знание, божественное женское начало." } },
  { id: 3, name: { en: "The Empress", ru: "Императрица" }, imageUrl: `${BASE_URL}03_empress.png`, description: { en: "Femininity, beauty, nature, nurturing.", ru: "Женственность, красота, природа, забота." } },
  { id: 4, name: { en: "The Emperor", ru: "Император" }, imageUrl: `${BASE_URL}04_emperor.png`, description: { en: "Authority, establishment, structure.", ru: "Власть, учреждение, структура." } },
  { id: 5, name: { en: "The Hierophant", ru: "Иерофант" }, imageUrl: `${BASE_URL}05_hierophant.png`, description: { en: "Spiritual wisdom, religious beliefs, tradition.", ru: "Духовная мудрость, религиозные верования, традиции." } },
  { id: 6, name: { en: "The Lovers", ru: "Влюбленные" }, imageUrl: `${BASE_URL}06_lovers.png`, description: { en: "Love, harmony, relationships, choices.", ru: "Любовь, гармония, отношения, выбор." } },
  { id: 7, name: { en: "The Chariot", ru: "Колесница" }, imageUrl: `${BASE_URL}07_chariot.png`, description: { en: "Control, willpower, success, action.", ru: "Контроль, сила воли, успех, действие." } },
  { id: 8, name: { en: "Strength", ru: "Сила" }, imageUrl: `${BASE_URL}08_strength.png`, description: { en: "Courage, persuasion, influence, compassion.", ru: "Смелость, убеждение, влияние, сострадание." } },
  { id: 9, name: { en: "The Hermit", ru: "Отшельник" }, imageUrl: `${BASE_URL}09_hermit.png`, description: { en: "Soul-searching, introspection, guidance.", ru: "Поиски души, самоанализ, руководство." } },
  { id: 10, name: { en: "Wheel of Fortune", ru: "Колесо Фортуны" }, imageUrl: `${BASE_URL}10_wheel_of_fortune.png`, description: { en: "Good luck, karma, life cycles, destiny.", ru: "Удача, карма, жизненные циклы, судьба." } },
  { id: 11, name: { en: "Justice", ru: "Справедливость" }, imageUrl: `${BASE_URL}11_justice.png`, description: { en: "Justice, fairness, truth, cause and effect.", ru: "Справедливость, честность, истина, причина и следствие." } },
  { id: 12, name: { en: "The Hanged Man", ru: "Повешенный" }, imageUrl: `${BASE_URL}12_hanged_man.png`, description: { en: "Pause, surrender, letting go, new perspectives.", ru: "Пауза, сдача, отпускание, новые перспективы." } },
  { id: 13, name: { en: "Death", ru: "Смерть" }, imageUrl: `${BASE_URL}13_death.png`, description: { en: "Endings, change, transformation, transition.", ru: "Окончания, перемены, трансформация, переход." } },
  { id: 14, name: { en: "Temperance", ru: "Умеренность" }, imageUrl: `${BASE_URL}14_temperance.png`, description: { en: "Balance, moderation, patience, purpose.", ru: "Баланс, умеренность, терпение, цель." } },
  { id: 15, name: { en: "The Devil", ru: "Дьявол" }, imageUrl: `${BASE_URL}15_devil.png`, description: { en: "Shadow self, attachment, addiction, restriction.", ru: "Теневое я, привязанность, зависимость, ограничение." } },
  { id: 16, name: { en: "The Tower", ru: "Башня" }, imageUrl: `${BASE_URL}16_tower.png`, description: { en: "Sudden change, upheaval, chaos, revelation.", ru: "Внезапные перемены, потрясения, хаос, откровение." } },
  { id: 17, name: { en: "The Star", ru: "Звезда" }, imageUrl: `${BASE_URL}17_star.png`, description: { en: "Hope, faith, purpose, renewal, spirituality.", ru: "Надежда, вера, цель, обновление, духовность." } },
  { id: 18, name: { en: "The Moon", ru: "Луна" }, imageUrl: `${BASE_URL}18_moon.png`, description: { en: "Illusion, fear, anxiety, subconscious.", ru: "Иллюзия, страх, беспокойство, подсознание." } },
  { id: 19, name: { en: "The Sun", ru: "Солнце" }, imageUrl: `${BASE_URL}19_sun.png`, description: { en: "Positivity, fun, warmth, success, vitality.", ru: "Позитив, веселье, тепло, успех, жизненная сила." } },
  { id: 20, name: { en: "Judgement", ru: "Суд" }, imageUrl: `${BASE_URL}20_judgement.png`, description: { en: "Judgement, rebirth, inner calling, absolution.", ru: "Суд, возрождение, внутренний зов, отпущение грехов." } },
  { id: 21, name: { en: "The World", ru: "Мир" }, imageUrl: `${BASE_URL}21_world.png`, description: { en: "Completion, integration, accomplishment, travel.", ru: "Завершение, интеграция, достижение, путешествие." } },
  { id: 22, name: { en: "The Hero", ru: "Герой" }, imageUrl: `${BASE_URL}22_hero.png`, description: { en: "Self-realization, courage, the journey within.", ru: "Самореализация, мужество, путешествие внутрь себя." } },
  { id: 23, name: { en: "White Card", ru: "Белая Карта" }, imageUrl: `${BASE_URL}23_white_card.png`, description: { en: "Unlimited potential, a clean slate, the unknown.", ru: "Неограниченный потенциал, чистый лист, неизвестность." } },

  // Wands
  { id: 24, name: { en: "Ace of Wands", ru: "Туз Жезлов" }, imageUrl: `${BASE_URL}wands_01_ace.png`, description: { en: "Inspiration, new opportunities, growth.", ru: "Вдохновение, новые возможности, рост." } },
  { id: 25, name: { en: "Two of Wands", ru: "Двойка Жезлов" }, imageUrl: `${BASE_URL}wands_02_two.png`, description: { en: "Future planning, progress, decisions.", ru: "Планирование будущего, прогресс, решения." } },
  { id: 26, name: { en: "Three of Wands", ru: "Тройка Жезлов" }, imageUrl: `${BASE_URL}wands_03_three.png`, description: { en: "Expansion, foresight, overseas opportunities.", ru: "Расширение, предвидение, зарубежные возможности." } },
  { id: 27, name: { en: "Four of Wands", ru: "Четверка Жезлов" }, imageUrl: `${BASE_URL}wands_04_four.png`, description: { en: "Celebration, harmony, marriage, home.", ru: "Праздник, гармония, брак, дом." } },
  { id: 28, name: { en: "Five of Wands", ru: "Пятерка Жезлов" }, imageUrl: `${BASE_URL}wands_05_five.png`, description: { en: "Conflict, disagreements, competition.", ru: "Конфликт, разногласия, соревнование." } },
  { id: 29, name: { en: "Six of Wands", ru: "Шестерка Жезлов" }, imageUrl: `${BASE_URL}wands_06_six.png`, description: { en: "Success, public recognition, victory.", ru: "Успех, общественное признание, победа." } },
  { id: 30, name: { en: "Seven of Wands", ru: "Семерка Жезлов" }, imageUrl: `${BASE_URL}wands_07_seven.png`, description: { en: "Challenge, competition, perseverance.", ru: "Вызов, соревнование, настойчивость." } },
  { id: 31, name: { en: "Eight of Wands", ru: "Восьмерка Жезлов" }, imageUrl: `${BASE_URL}wands_08_eight.png`, description: { en: "Movement, fast paced change, action.", ru: "Движение, быстрые перемены, действие." } },
  { id: 32, name: { en: "Nine of Wands", ru: "Девятка Жезлов" }, imageUrl: `${BASE_URL}wands_09_nine.png`, description: { en: "Resilience, courage, persistence, test of faith.", ru: "Устойчивость, мужество, настойчивость, испытание веры." } },
  { id: 33, name: { en: "Ten of Wands", ru: "Десятка Жезлов" }, imageUrl: `${BASE_URL}wands_10_ten.png`, description: { en: "Burden, extra responsibility, hard work.", ru: "Бремя, дополнительная ответственность, тяжелая работа." } },
  { id: 34, name: { en: "Page of Wands", ru: "Паж Жезлов" }, imageUrl: `${BASE_URL}wands_11_page.png`, description: { en: "Enthusiasm, exploration, free spirit.", ru: "Энтузиазм, исследование, свободный дух." } },
  { id: 35, name: { en: "Knight of Wands", ru: "Рыцарь Жезлов" }, imageUrl: `${BASE_URL}wands_12_knight.png`, description: { en: "Energy, passion, inspired action, adventure.", ru: "Энергия, страсть, вдохновенное действие, приключение." } },
  { id: 36, name: { en: "Queen of Wands", ru: "Королева Жезлов" }, imageUrl: `${BASE_URL}wands_13_queen.png`, description: { en: "Courage, confidence, independence.", ru: "Мужество, уверенность, независимость." } },
  { id: 37, name: { en: "King of Wands", ru: "Король Жезлов" }, imageUrl: `${BASE_URL}wands_14_king.png`, description: { en: "Natural-born leader, vision, entrepreneur.", ru: "Прирожденный лидер, видение, предприниматель." } },

  // Cups
  { id: 38, name: { en: "Ace of Cups", ru: "Туз Кубков" }, imageUrl: `${BASE_URL}cups_01_ace.png`, description: { en: "Love, new relationships, compassion.", ru: "Любовь, новые отношения, сострадание." } },
  { id: 39, name: { en: "Two of Cups", ru: "Двойка Кубков" }, imageUrl: `${BASE_URL}cups_02_two.png`, description: { en: "Unified love, partnership, mutual attraction.", ru: "Единая любовь, партнерство, взаимное притяжение." } },
  { id: 40, name: { en: "Three of Cups", ru: "Тройка Кубков" }, imageUrl: `${BASE_URL}cups_03_three.png`, description: { en: "Celebration, friendship, creativity, community.", ru: "Праздник, дружба, творчество, сообщество." } },
  { id: 41, name: { en: "Four of Cups", ru: "Четверка Кубков" }, imageUrl: `${BASE_URL}cups_04_four.png`, description: { en: "Meditation, contemplation, apathy.", ru: "Медитация, созерцание, апатия." } },
  { id: 42, name: { en: "Five of Cups", ru: "Пятерка Кубков" }, imageUrl: `${BASE_URL}cups_05_five.png`, description: { en: "Regret, failure, disappointment, pessimism.", ru: "Сожаление, неудача, разочарование, пессимизм." } },
  { id: 43, name: { en: "Six of Cups", ru: "Шестерка Кубков" }, imageUrl: `${BASE_URL}cups_06_six.png`, description: { en: "Revisiting the past, childhood memories, innocence.", ru: "Возвращение в прошлое, детские воспоминания, невинность." } },
  { id: 44, name: { en: "Seven of Cups", ru: "Семерка Кубков" }, imageUrl: `${BASE_URL}cups_07_seven.png`, description: { en: "Opportunities, choices, wishful thinking, illusion.", ru: "Возможности, выбор, принятие желаемого за действительное, иллюзия." } },
  { id: 45, name: { en: "Eight of Cups", ru: "Восьмерка Кубков" }, imageUrl: `${BASE_URL}cups_08_eight.png`, description: { en: "Disappointment, abandonment, withdrawal.", ru: "Разочарование, покинутость, уход." } },
  { id: 46, name: { en: "Nine of Cups", ru: "Девятка Кубков" }, imageUrl: `${BASE_URL}cups_09_nine.png`, description: { en: "Contentment, satisfaction, gratitude.", ru: "Удовлетворенность, удовлетворение, благодарность." } },
  { id: 47, name: { en: "Ten of Cups", ru: "Десятка Кубков" }, imageUrl: `${BASE_URL}cups_10_ten.png`, description: { en: "Divine love, blissful relationships, harmony.", ru: "Божественная любовь, блаженные отношения, гармония." } },
  { id: 48, name: { en: "Page of Cups", ru: "Паж Кубков" }, imageUrl: `${BASE_URL}cups_11_page.png`, description: { en: "Creative opportunities, intuitive messages.", ru: "Творческие возможности, интуитивные сообщения." } },
  { id: 49, name: { en: "Knight of Cups", ru: "Рыцарь Кубков" }, imageUrl: `${BASE_URL}cups_12_knight.png`, description: { en: "Romance, charm, imagination, beauty.", ru: "Романтика, обаяние, воображение, красота." } },
  { id: 50, name: { en: "Queen of Cups", ru: "Королева Кубков" }, imageUrl: `${BASE_URL}cups_13_queen.png`, description: { en: "Compassionate, caring, intuitive, flowing.", ru: "Сострадательная, заботливая, интуитивная, плавная." } },
  { id: 51, name: { en: "King of Cups", ru: "Король Кубков" }, imageUrl: `${BASE_URL}cups_14_king.png`, description: { en: "Emotionally balanced, compassionate, diplomatic.", ru: "Эмоционально сбалансированный, сострадательный, дипломатичный." } },

  // Swords
  { id: 52, name: { en: "Ace of Swords", ru: "Туз Мечей" }, imageUrl: `${BASE_URL}swords_01_ace.png`, description: { en: "Breakthroughs, new ideas, mental clarity.", ru: "Прорывы, новые идеи, ясность ума." } },
  { id: 53, name: { en: "Two of Swords", ru: "Двойка Мечей" }, imageUrl: `${BASE_URL}swords_02_two.png`, description: { en: "Difficult decisions, weighing up options, avoidance.", ru: "Трудные решения, взвешивание вариантов, избегание." } },
  { id: 54, name: { en: "Three of Swords", ru: "Тройка Мечей" }, imageUrl: `${BASE_URL}swords_03_three.png`, description: { en: "Heartbreak, emotional pain, sorrow, grief.", ru: "Разбитое сердце, эмоциональная боль, печаль, горе." } },
  { id: 55, name: { en: "Four of Swords", ru: "Четверка Мечей" }, imageUrl: `${BASE_URL}swords_04_four.png`, description: { en: "Rest, relaxation, meditation, contemplation.", ru: "Отдых, расслабление, медитация, созерцание." } },
  { id: 56, name: { en: "Five of Swords", ru: "Пятерка Мечей" }, imageUrl: `${BASE_URL}swords_05_five.png`, description: { en: "Conflict, competition, win at all costs.", ru: "Конфликт, соревнование, победа любой ценой." } },
  { id: 57, name: { en: "Six of Swords", ru: "Шестерка Мечей" }, imageUrl: `${BASE_URL}swords_06_six.png`, description: { en: "Transition, change, rite of passage.", ru: "Переход, изменение, обряд посвящения." } },
  { id: 58, name: { en: "Seven of Swords", ru: "Семерка Мечей" }, imageUrl: `${BASE_URL}swords_07_seven.png`, description: { en: "Betrayal, deception, getting away with something.", ru: "Предательство, обман, выход сухим из воды." } },
  { id: 59, name: { en: "Eight of Swords", ru: "Восьмерка Мечей" }, imageUrl: `${BASE_URL}swords_08_eight.png`, description: { en: "Negative thoughts, self-imposed restriction.", ru: "Негативные мысли, самоограничение." } },
  { id: 60, name: { en: "Nine of Swords", ru: "Девятка Мечей" }, imageUrl: `${BASE_URL}swords_09_nine.png`, description: { en: "Anxiety, worry, fear, depression, nightmares.", ru: "Беспокойство, тревога, страх, депрессия, кошмары." } },
  { id: 61, name: { en: "Ten of Swords", ru: "Десятка Мечей" }, imageUrl: `${BASE_URL}swords_10_ten.png`, description: { en: "Painful endings, deep wounds, betrayal.", ru: "Болезненные окончания, глубокие раны, предательство." } },
  { id: 62, name: { en: "Page of Swords", ru: "Паж Мечей" }, imageUrl: `${BASE_URL}swords_11_page.png`, description: { en: "New ideas, curiosity, thirst for knowledge.", ru: "Новые идеи, любопытство, жажда знаний." } },
  { id: 63, name: { en: "Knight of Swords", ru: "Рыцарь Мечей" }, imageUrl: `${BASE_URL}swords_12_knight.png`, description: { en: "Ambitious, action-oriented, fast-thinking.", ru: "Амбициозный, ориентированный на действие, быстро мыслящий." } },
  { id: 64, name: { en: "Queen of Swords", ru: "Королева Мечей" }, imageUrl: `${BASE_URL}swords_13_queen.png`, description: { en: "Independent, unbiased judgement, clear boundaries.", ru: "Независимая, беспристрастное суждение, ясные границы." } },
  { id: 65, name: { en: "King of Swords", ru: "Король Мечей" }, imageUrl: `${BASE_URL}swords_14_king.png`, description: { en: "Mental clarity, intellectual power, authority.", ru: "Ясность ума, интеллектуальная мощь, авторитет." } },

  // Pentacles
  { id: 66, name: { en: "Ace of Pentacles", ru: "Туз Пентаклей" }, imageUrl: `${BASE_URL}pentacles_01_ace.png`, description: { en: "A new financial or career opportunity.", ru: "Новая финансовая или карьерная возможность." } },
  { id: 67, name: { en: "Two of Pentacles", ru: "Двойка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_02_two.png`, description: { en: "Multiple priorities, time management, adaptability.", ru: "Множество приоритетов, управление временем, адаптивность." } },
  { id: 68, name: { en: "Three of Pentacles", ru: "Тройка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_03_three.png`, description: { en: "Teamwork, collaboration, learning.", ru: "Командная работа, сотрудничество, обучение." } },
  { id: 69, name: { en: "Four of Pentacles", ru: "Четверка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_04_four.png`, description: { en: "Saving money, security, conservatism.", ru: "Экономия денег, безопасность, консерватизм." } },
  { id: 70, name: { en: "Five of Pentacles", ru: "Пятерка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_05_five.png`, description: { en: "Financial loss, poverty, isolation.", ru: "Финансовые потери, бедность, изоляция." } },
  { id: 71, name: { en: "Six of Pentacles", ru: "Шестерка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_06_six.png`, description: { en: "Giving, receiving, sharing wealth.", ru: "Дарение, получение, разделение богатства." } },
  { id: 72, name: { en: "Seven of Pentacles", ru: "Семерка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_07_seven.png`, description: { en: "Long-term view, sustainable results, perseverance.", ru: "Долгосрочная перспектива, устойчивые результаты, настойчивость." } },
  { id: 73, name: { en: "Eight of Pentacles", ru: "Восьмерка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_08_eight.png`, description: { en: "Apprenticeship, repetitive tasks, mastery.", ru: "Ученичество, повторяющиеся задачи, мастерство." } },
  { id: 74, name: { en: "Nine of Pentacles", ru: "Девятка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_09_nine.png`, description: { en: "Abundance, luxury, self-sufficiency.", ru: "Изобилие, роскошь, самодостаточность." } },
  { id: 75, name: { en: "Ten of Pentacles", ru: "Десятка Пентаклей" }, imageUrl: `${BASE_URL}pentacles_10_ten.png`, description: { en: "Wealth, financial security, family, legacy.", ru: "Богатство, финансовая безопасность, семья, наследие." } },
  { id: 76, name: { en: "Page of Pentacles", ru: "Паж Пентаклей" }, imageUrl: `${BASE_URL}pentacles_11_page.png`, description: { en: "Manifestation, financial opportunity, skill development.", ru: "Проявление, финансовые возможности, развитие навыков." } },
  { id: 77, name: { en: "Knight of Pentacles", ru: "Рыцарь Пентаклей" }, imageUrl: `${BASE_URL}pentacles_12_knight.png`, description: { en: "Hard work, productivity, routine.", ru: "Тяжелая работа, производительность, рутина." } },
  { id: 78, name: { en: "Queen of Pentacles", ru: "Королева Пентаклей" }, imageUrl: `${BASE_URL}pentacles_13_queen.png`, description: { en: "Nurturing, practical, providing financially.", ru: "Заботливая, практичная, обеспечивающая финансово." } },
  { id: 79, name: { en: "King of Pentacles", ru: "Король Пентаклей" }, imageUrl: `${BASE_URL}pentacles_14_king.png`, description: { en: "Wealth, business, leadership, security.", ru: "Богатство, бизнес, лидерство, безопасность." } },
];

export const SPREADS: Spread[] = [
    {
        id: 'one-card',
        name: (lang: Language) => lang === 'en' ? 'Card of the Day' : 'Карта Дня',
        cardCount: 1,
        positions: (lang: Language) => [lang === 'en' ? 'The energy of your day' : 'Энергия вашего дня'],
    },
    {
        id: 'three-card',
        name: (lang: Language) => lang === 'en' ? 'Three Cards' : 'Три Карты',
        cardCount: 3,
        positions: (lang: Language) => lang === 'en' ? ['Past', 'Present', 'Future'] : ['Прошлое', 'Настоящее', 'Будущее'],
    },
    {
        id: 'hero-step',
        name: (lang: Language) => lang === 'en' ? "Hero's Path Step" : 'Шаг на Пути Героя',
        cardCount: 5,
        positions: (lang: Language) => lang === 'en' ? ['1. The Fool (Challenge)', '2. The Magician (Tool)', '3. The Devil (Temptation)', '4. The Tower (Revelation)', '5. The Star (Guidance)'] : ['1. Шут (Вызов)', '2. Маг (Инструмент)', '3. Дьявол (Искушение)', '4. Башня (Откровение)', '5. Звезда (Направление)'],
    }
];

export const localization = {
  en: {
    navHome: "Home",
    navReadings: "Readings",
    navEncyclopedia: "Encyclopedia",
    navTest: "Who are you?",
    navBlog: "Blog",
    navWorkshop: "Workshop",
    navShop: "Shop",
    navContact: "Contact",
    homeTitle: "Arcana Tuner of the Day",
    homeSubtitle: "The philosophy of the deck is a journey of self-discovery, where each card is a step on the path to understanding your inner hero.",
    homeCTA: "Go to Readings",
    readingsTitle: "A Journey, Not a Spread",
    readingsSubtitle: "Choose a spread to begin your journey of introspection.",
    drawCards: "Draw Cards",
    getInterpretation: "Get AI Interpretation",
    readingResult: "Your Reading:",
    audioPlayback: "Play Audio Interpretation",
    loadingInterpretation: "AI is contemplating your destiny...",
    generatingAudio: "Generating audio...",
    encyclopediaTitle: "Web of Meanings",
    encyclopediaSearch: "Search Arcana...",
    cardDetailRelated: "Related Arcana",
    testTitle: "Who are you in Tarot?",
    testSubtitle: "Describe yourself, your feelings, or your situation. The AI will analyze your text and select an Arcana that reflects your essence.",
    testPlaceholder: "Enter your text here...",
    testAction: "Find My Arcana",
    testResult: "Your Personal Arcana:",
    generatingPortrait: "Generating your psychological portrait...",
    generatingImage: "Generating your unique image...",
    personalVision: "Your Personal Vision",
    personalVisionDescription: "An AI-generated reflection of your energy and the {cardName} archetype.",
    blogTitle: "Urban Tarot",
    workshopTitle: "Creator's Workshop",
    shopTitle: "Shop",
    shopAction: "Buy on Amazon",
    contactTitle: "Contact Us",
    contactFormName: "Your Name",
    contactFormEmail: "Your Email",
    contactFormMessage: "Your Message",
    contactFormSend: "Send Message",
    contactTelegram: "Join our Telegram Group",
    footerText: "© 2024 Hero's Journey Tarot. All rights reserved.",
  },
  ru: {
    navHome: "Главная",
    navReadings: "Гадания",
    navEncyclopedia: "Энциклопедия",
    navTest: "Кто ты в Таро?",
    navBlog: "Блог",
    navWorkshop: "Мастерская",
    navShop: "Магазин",
    navContact: "Контакты",
    homeTitle: "Аркан-Настройщик Дня",
    homeSubtitle: "Философия колоды — это путешествие к себе, где каждая карта — это шаг на пути к пониманию своего внутреннего героя.",
    homeCTA: "Перейти к гаданиям",
    readingsTitle: "Путешествие, а не расклад",
    readingsSubtitle: "Выберите расклад, чтобы начать ваше путешествие вглубь себя.",
    drawCards: "Вытянуть Карты",
    getInterpretation: "Получить AI-толкование",
    readingResult: "Ваш Расклад:",
    audioPlayback: "Прослушать толкование",
    loadingInterpretation: "ИИ размышляет над вашей судьбой...",
    generatingAudio: "Генерация аудио...",
    encyclopediaTitle: "Паутина Смыслов",
    encyclopediaSearch: "Поиск по Арканам...",
    cardDetailRelated: "Связанные Арканы",
    testTitle: "Кто ты в Таро?",
    testSubtitle: "Опишите себя, свои чувства или ситуацию. ИИ проанализирует ваш текст и подберет Аркан, отражающий вашу суть.",
    testPlaceholder: "Введите ваш текст...",
    testAction: "Найти мой Аркан",
    testResult: "Ваш Персональный Аркан:",
    generatingPortrait: "Создание вашего психологического портрета...",
    generatingImage: "Генерация вашего уникального образа...",
    personalVision: "Ваше личное видение",
    personalVisionDescription: "Образ, сгенерированный ИИ, как отражение вашей энергии и архетипа {cardName}.",
    blogTitle: "Городское Таро",
    workshopTitle: "Мастерская Создателя",
    shopTitle: "Магазин",
    shopAction: "Купить на Amazon",
    contactTitle: "Свяжитесь с нами",
    contactFormName: "Ваше Имя",
    contactFormEmail: "Ваш Email",
    contactFormMessage: "Ваше Сообщение",
    contactFormSend: "Отправить Сообщение",
    contactTelegram: "Присоединяйтесь к нашей Telegram-группе",
    footerText: "© 2024 Таро: Путешествие Героя. Все права защищены.",
  }
};